wandb_version: 1

ID:
  desc: null
  value: Simon
architecture:
  desc: null
  value: Multi Input ResNet18 Spectral
dataset:
  desc: null
  value: COVID-19 Audio Classification
learning_rate:
  desc: null
  value: 0.0001
step_size:
  desc: null
  value: 3
weight_decay:
  desc: null
  value: 0.001
optimizer:
  desc: null
  value: adam
scheduler:
  desc: null
  value: steplr
gamma:
  desc: null
  value: 0.5
epochs:
  desc: null
  value: 25
factor:
  desc: null
  value: 0.1
threshold:
  desc: null
  value: 0.001
patience:
  desc: null
  value: 2
cooldown:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1712070007.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.11.6
      5: 0.16.4
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
